# Generated by Django 4.1.5 on 2023-05-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wl_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='wish_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Идентификатор желания'),
        ),
    ]
