# Generated by Django 4.1.5 on 2023-01-16 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wl_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=250, null=True, verbose_name='Идентификатор сессии')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Названий списка')),
            ],
        ),
        migrations.RemoveField(
            model_name='wish',
            name='text',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='user',
        ),
        migrations.AddField(
            model_name='wish',
            name='wishlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to='wl_app.wishlist'),
        ),
    ]
