# Generated by Django 4.1.5 on 2023-01-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wl_app', '0002_wishlist_remove_wish_text_remove_wish_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='is_given',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
